# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts-alpine3.17

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build_image:
  only:
    - master
  stage: build
  script:
    - echo "Building image..."
    - echo "Tagging the docker image"    

push_image:
  only:
    - master
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging into docker registry..."
    - echo "Pushing docker image to registry..."

test_async:
  stage: test
  script:
    - chmod +x ./build-scripts/tests.sh
    - ./build-scripts/tests.sh
    - echo "Running tests... Done perfectly - no bugs at all"
  before_script:
    - echo "Preparing test data..." 
  after_script:
    - echo "Cleaning temporary files..."
    # - node ./specs/start.js ./specs/async.spec.js

deploy:
  only:
    - master
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production