# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts-alpine

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_REPOSITORY: docker.io/zemaclick/imagine-ui
  IMAGE_TAG: v1.0

build:
  tags:
    - docker
    - local
  stage: build
  script:
    - echo "Building image..."
    - chmod +x ./build-scripts/build.sh
    - ./build-scripts/build.sh

test_unit_tests:
  stage: test
  tags:
    - linux
    - docker
    - local
  before_script:
    - cd src
    - npm install
  script:
    - npm test

build_image:
  only:
    - master
  tags:
    - docker
  stage: deploy
  script:
    - echo "Building image..."
    - echo "Tagging the docker image $IMAGE_REPOSITORY:$IMAGE_TAG"

push_image:
  only:
    - master
  tags:
    - docker
  stage: deploy
  needs:
    - build_image
  script:
    - echo "Logging into docker registry..."
    - echo "Pushing docker image $IMAGE_REPOSITORY:$IMAGE_TAG to registry..."

deploy:
  only:
    - master
  stage: deploy
  needs: 
    - push_image
  script: echo "Define your deployment script!"
  environment: production