version: '3.9'
services:
  imagine-web:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    container_name: imagine-web
    ports:
      - 80:80
    environment:
      - REACT_APP_IMAGINE_API_URI=http://api.aiexpression.net
    restart: unless-stopped