version: '3.9'
services:
  imagine-web:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    container_name: imagine-web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_IMAGINE_API_URI=http://imaginearts.net
    restart: unless-stopped

networks:
  default:
    external: true
    name: imagine