version: '3.9'
services:
  imagine-web:
    image: imagine-web:0.1.0
    build: .
    container_name: imagine-web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_IMAGINE_API_URI=http://95.30.222.161:52346
    restart: unless-stopped

networks:
  default:
    external: true
    name: imagine